a = float(input())
b = float(input())
d = float(input())
e = float(input())
c = float(input())
f = float(input())
y = (a * f - c * d) / (a * e - b * d)
x = (c * e - b * f) / (a * e - b * d)
print(x, y)
